# Generated by Django 4.2.18 on 2025-02-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonr', models.CharField(max_length=6, verbose_name='Automobilio numeris')),
            ],
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30, verbose_name='Vardas')),
                ('l_name', models.CharField(max_length=30, verbose_name='Pavardė')),
                ('numeris', models.CharField(max_length=30, verbose_name='Numeris')),
            ],
        ),
        migrations.CreateModel(
            name='Modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelis', models.CharField(help_text='Įveskite automobilio modelį', max_length=20, verbose_name='modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Paslaugos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paslauga', models.CharField(max_length=50, verbose_name='Paslauga')),
                ('aprasymas', models.CharField(help_text='Aprašykite paslaugą', max_length=500, verbose_name='Aprašymas')),
                ('kaina', models.FloatField(max_length=30, verbose_name='Paslaugos kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Užsakymo data')),
                ('status', models.CharField(blank=True, choices=[('a', 'Apdorojamas'), ('p', 'Priimtas'), ('v', 'Vykdomas'), ('i', 'Įvykdytas')], default='a', help_text='Užsakymo statusas', max_length=1, verbose_name='Statusas')),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.car')),
            ],
        ),
        migrations.CreateModel(
            name='PaslaugaUzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paslaugu_kiekis', models.IntegerField(help_text='Kiek kartų ši paslauga bus vykdoma', max_length=3, verbose_name='Paslagų kiekis')),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.paslaugos')),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.uzsakymas')),
            ],
        ),
        migrations.CreateModel(
            name='Gamintojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamintojas', models.CharField(max_length=30, verbose_name='Gamintojas')),
                ('modelis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.modelis')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='gamintojas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.gamintojas'),
        ),
        migrations.AddField(
            model_name='car',
            name='klientas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.klientas'),
        ),
    ]
