# Generated by Django 4.2.18 on 2025-02-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paslaugauzsakymas',
            name='paslaugu_kiekis',
            field=models.IntegerField(help_text='Kiek kartų ši paslauga bus vykdoma', verbose_name='Paslagų kiekis'),
        ),
    ]
