# Generated by Django 4.2.18 on 2025-02-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_alter_paslaugauzsakymas_paslaugu_kiekis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='gamintojas',
        ),
        migrations.RemoveField(
            model_name='gamintojas',
            name='modelis',
        ),
        migrations.AddField(
            model_name='car',
            name='modelis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.modelis'),
        ),
        migrations.AddField(
            model_name='modelis',
            name='gamintojas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.gamintojas'),
        ),
    ]
