# Generated by Django 4.2.18 on 2025-02-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_remove_car_gamintojas_remove_gamintojas_modelis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='gamintojas',
            options={'verbose_name': 'Gamintojas', 'verbose_name_plural': 'Gamintojai'},
        ),
        migrations.AlterModelOptions(
            name='klientas',
            options={'verbose_name': 'Klientas', 'verbose_name_plural': 'Klientai'},
        ),
        migrations.AlterModelOptions(
            name='modelis',
            options={'verbose_name': 'Modelis', 'verbose_name_plural': 'Modeliai'},
        ),
        migrations.AlterModelOptions(
            name='paslaugauzsakymas',
            options={'verbose_name': 'Užsakymo eilutė', 'verbose_name_plural': 'Užsakymų eilutės'},
        ),
        migrations.AlterModelOptions(
            name='paslaugos',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AddField(
            model_name='car',
            name='car_img',
            field=models.ImageField(blank=True, null=True, upload_to='cars', verbose_name='Auto img'),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='modelis',
            field=models.CharField(help_text='Įveskite automobilio modelį', max_length=20, verbose_name='Modelis'),
        ),
    ]
