# Generated by Django 4.2.18 on 2025-02-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisas', '0004_alter_car_options_alter_gamintojas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='uzsakovas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
