from autoservisas.models import Modelis, Klientas, Gamintojas, Car, Paslaugos, Uzsakymas, PaslaugaUzsakymas

gamintojai = [
    Gamintojas.objects.create(gamintojas='Nissan'),
    Gamintojas.objects.create(gamintojas='Honda'),
    Gamintojas.objects.create(gamintojas='Toyota'),
    Gamintojas.objects.create(gamintojas='Volvo'),
    Gamintojas.objects.create(gamintojas='Skoda'),
    Gamintojas.objects.create(gamintojas='Mazda'),
    Gamintojas.objects.create(gamintojas='Ford'),
    Gamintojas.objects.create(gamintojas='Chevrolet'),
    Gamintojas.objects.create(gamintojas='Dodge'),
    Gamintojas.objects.create(gamintojas='Audi'),
    Gamintojas.objects.create(gamintojas='Mitsubishi'),
]

modeliai = [
    Modelis.objects.create(modelis='Skyline', gamintojas=gamintojai[0]),
    Modelis.objects.create(modelis='Integra', gamintojas=gamintojai[1]),
    Modelis.objects.create(modelis='Accord', gamintojas=gamintojai[1]),
    Modelis.objects.create(modelis='Superb', gamintojas=gamintojai[4]),
    Modelis.objects.create(modelis='RX-7', gamintojas=gamintojai[5]),
    Modelis.objects.create(modelis='S80', gamintojas=gamintojai[3]),
    Modelis.objects.create(modelis='S60', gamintojas=gamintojai[3]),
    Modelis.objects.create(modelis='C70', gamintojas=gamintojai[3]),
    Modelis.objects.create(modelis='Civic', gamintojas=gamintojai[1]),
    Modelis.objects.create(modelis='Mustang', gamintojas=gamintojai[6]),
    Modelis.objects.create(modelis='Camry', gamintojas=gamintojai[2]),
    Modelis.objects.create(modelis='Impala', gamintojas=gamintojai[7]),
    Modelis.objects.create(modelis='Corolla', gamintojas=gamintojai[2]),
    Modelis.objects.create(modelis='GT-R', gamintojas=gamintojai[0]),
    Modelis.objects.create(modelis='Charger', gamintojas=gamintojai[8]),
    Modelis.objects.create(modelis='A4', gamintojas=gamintojai[9]),
    Modelis.objects.create(modelis='A6', gamintojas=gamintojai[9]),
    Modelis.objects.create(modelis='A7', gamintojas=gamintojai[9]),
    Modelis.objects.create(modelis='A8', gamintojas=gamintojai[9]),
    Modelis.objects.create(modelis='A5', gamintojas=gamintojai[9]),
    Modelis.objects.create(modelis='RS7', gamintojas=gamintojai[9]),
    Modelis.objects.create(modelis='Eclipse', gamintojas=gamintojai[10]),
    Modelis.objects.create(modelis='Lancer', gamintojas=gamintojai[10]),
    Modelis.objects.create(modelis='Challenger', gamintojas=gamintojai[8]),
    Modelis.objects.create(modelis='Mondeo', gamintojas=gamintojai[6]),

]

klientai = [
    Klientas.objects.create(f_name='Adomas', l_name='Adomaitis', numeris=37068913541),
    Klientas.objects.create(f_name='Harry', l_name='Potter', numeris=37068877214),
    Klientas.objects.create(f_name='Lukas', l_name='Lukinis', numeris=37068874364),
    Klientas.objects.create(f_name='Geralt', l_name='Rivianator', numeris=37065795465),
    Klientas.objects.create(f_name='Jonas', l_name='Biliūnas', numeris=37068874364),
    Klientas.objects.create(f_name='Luke', l_name='Skywalker', numeris=37064612875),
    Klientas.objects.create(f_name='Jon', l_name='Snow', numeris=37063471412),
    Klientas.objects.create(f_name='Jack', l_name='Sparrow', numeris=37069896635),
    Klientas.objects.create(f_name='Cat', l_name='Kitten', numeris=37065425845),
    Klientas.objects.create(f_name='Dexter', l_name='Morgan', numeris=37064587235),
]

cars = [
    Car.objects.create(autonr='ATC456', modelis=modeliai[0], klientas=klientai[0]),
    Car.objects.create(autonr='IYU498', modelis=modeliai[1], klientas=klientai[1]),
    Car.objects.create(autonr='CVC434', modelis=modeliai[2], klientas=klientai[2]),
    Car.objects.create(autonr='BBB978', modelis=modeliai[5], klientas=klientai[3]),
    Car.objects.create(autonr='JUT499', modelis=modeliai[4], klientas=klientai[4]),
    Car.objects.create(autonr='JAS133', modelis=modeliai[3], klientas=klientai[5]),
    Car.objects.create(autonr='QQH706', modelis=modeliai[6], klientas=klientai[6]),
    Car.objects.create(autonr='TDG789', modelis=modeliai[7], klientas=klientai[7]),
    Car.objects.create(autonr='GAD877', modelis=modeliai[8], klientas=klientai[8]),
    Car.objects.create(autonr='SQL045', modelis=modeliai[9], klientas=klientai[9]),
    Car.objects.create(autonr='UDK788', modelis=modeliai[10], klientas=klientai[9]),
    Car.objects.create(autonr='KTU711', modelis=modeliai[-2], klientas=klientai[1]),
    Car.objects.create(autonr='TBM712', modelis=modeliai[-3], klientas=klientai[6]),
]

services = [
    Paslaugos.objects.create(paslauga='Ratų balansavimas',
                             aprasymas='Ratų balansavimas automobiliui',
                             kaina=40),
    Paslaugos.objects.create(paslauga='Stiklo keitimas',
                             aprasymas='Priekinio šildomo stiklo keitimas nauju',
                             kaina=540),
    Paslaugos.objects.create(paslauga='Automobilio poliravimas',
                             aprasymas='Viso Automobilio poliravimas',
                             kaina=140),
    Paslaugos.objects.create(paslauga='Langų tamsinimas',
                             aprasymas='Langų tamsinimas',
                             kaina=70),
    Paslaugos.objects.create(paslauga='Stabdžių diskų ketimas',
                             aprasymas='Priekinių stabdžių disku ir kaladėlių keitimas',
                             kaina=290),
    Paslaugos.objects.create(paslauga='Variklio alyvos keitimas',
                             aprasymas='Variklio alyvos keitimas bei tepalų, '
                                       'kuro, oro, salono filtrų keitimas',
                             kaina=130),
    Paslaugos.objects.create(paslauga='Slenksčių virinimas',
                             aprasymas='Automobilio slenksčių virinimas',
                             kaina=250),
    Paslaugos.objects.create(paslauga='Turbinos restaurivmas',
                             aprasymas='Turbinos perrinkimas ir jos detalių tvarkymas, pakeitimas',
                             kaina=515),
]

uzsakymai = [
    Uzsakymas.objects.create(data='2025-02-03', status='i', automobilis=cars[0]),
    Uzsakymas.objects.create(data='2025-02-03', status='p', automobilis=cars[1]),
    Uzsakymas.objects.create(data='2025-02-03', status='v', automobilis=cars[2]),
    Uzsakymas.objects.create(data='2025-02-03', status='v', automobilis=cars[3]),
    Uzsakymas.objects.create(data='2025-02-03', status='i', automobilis=cars[4]),
    Uzsakymas.objects.create(data='2025-02-03', status='i', automobilis=cars[5]),
    Uzsakymas.objects.create(data='2025-02-04', status='v', automobilis=cars[6]),
    Uzsakymas.objects.create(data='2025-02-04', status='p', automobilis=cars[7]),
    Uzsakymas.objects.create(data='2025-02-04', status='v', automobilis=cars[8]),
    Uzsakymas.objects.create(data='2025-02-04', status='p', automobilis=cars[9]),
    Uzsakymas.objects.create(data='2025-02-04', status='a', automobilis=cars[10]),
    Uzsakymas.objects.create(data='2025-02-06', status='v', automobilis=cars[11]),
    Uzsakymas.objects.create(data='2025-02-06', status='p', automobilis=cars[12]),
    Uzsakymas.objects.create(data='2025-02-06', status='a', automobilis=cars[0]),
    Uzsakymas.objects.create(data='2025-02-06', status='p', automobilis=cars[1]),
    Uzsakymas.objects.create(data='2025-02-09', status='p', automobilis=cars[2]),
    Uzsakymas.objects.create(data='2025-02-09', status='a', automobilis=cars[3]),
    Uzsakymas.objects.create(data='2025-02-09', status='v', automobilis=cars[4]),
    Uzsakymas.objects.create(data='2025-02-09', status='p', automobilis=cars[5]),
    Uzsakymas.objects.create(data='2025-02-08', status='a', automobilis=cars[6]),
    Uzsakymas.objects.create(data='2025-02-08', status='a', automobilis=cars[6]),
    Uzsakymas.objects.create(data='2025-02-08', status='p', automobilis=cars[9]),
]

paslauos_uzsakymai = [
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[21]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[1], uzsakymas=uzsakymai[21]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[3], uzsakymas=uzsakymai[20]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[2], uzsakymas=uzsakymai[19]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[4], uzsakymas=uzsakymai[0]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[0]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[5], uzsakymas=uzsakymai[0]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[18]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[7], uzsakymas=uzsakymai[18]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[17]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[3], uzsakymas=uzsakymai[17]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[16]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[7], uzsakymas=uzsakymai[15]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[3], uzsakymas=uzsakymai[14]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=3, paslauga=services[6], uzsakymas=uzsakymai[13]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[6], uzsakymas=uzsakymai[12]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[11]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[7], uzsakymas=uzsakymai[10]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[9]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[8]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[1], uzsakymas=uzsakymai[8]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[10]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[0], uzsakymas=uzsakymai[15]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[3], uzsakymas=uzsakymai[4]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[6]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[1], uzsakymas=uzsakymai[7]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[7]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=3, paslauga=services[6], uzsakymas=uzsakymai[7]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=3, paslauga=services[0], uzsakymas=uzsakymai[4]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[6], uzsakymas=uzsakymai[4]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[12]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[1], uzsakymas=uzsakymai[6]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[1]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[1], uzsakymas=uzsakymai[3]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=2, paslauga=services[0], uzsakymas=uzsakymai[5]),
    PaslaugaUzsakymas.objects.create(paslaugu_kiekis=1, paslauga=services[5], uzsakymas=uzsakymai[6]),
]
